[workspace]
resolver = "2"

members = [
    "memcrs"
    #"memclt"
]

[profile.release]
opt-level = 3
debug = "line-tables-only"
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.dev]
debug = true
opt-level = 0
